# harsha-dev-1 site
# Authored via AIO Launchpad. subscription, location, country inherited from shared/germany.yaml

apiVersion: siteops/v1
kind: Site
name: harsha-dev-1
inherits: shared/germany.yaml
resourceGroup: rg-harsha-dev-1
labels:
  environment: dev
parameters:
  clusterName: harsha-dev-1-arc
  brokerConfig:
    frontendReplicas: 1
    frontendWorkers: 1
    backendRedundancyFactor: 2
    backendWorkers: 1
    backendPartitions: 1
    memoryProfile: Low
