# Munich Development Site

apiVersion: siteops/v1
kind: Site
name: munich-dev
inherits: shared/germany.yaml

# subscription, location, country inherited from shared/germany.yaml
resourceGroup: rg-iot-munich-dev

labels:
  environment: dev
  city: Munich

parameters:
  clusterName: munich-dev-arc
  brokerConfig:
    frontendReplicas: 1
    frontendWorkers: 1
    backendRedundancyFactor: 2
    backendWorkers: 1
    backendPartitions: 1
    memoryProfile: Low
