# Seattle Production Site

apiVersion: siteops/v1
kind: Site
name: seattle-prod
inherits: shared/usa-west.yaml

# subscription, location, country inherited from shared/usa-west.yaml
resourceGroup: rg-iot-seattle-prod

labels:
  environment: prod
  city: Seattle

parameters:
  clusterName: seattle-prod-arc
  brokerConfig:
    frontendReplicas: 4
    frontendWorkers: 2
    backendRedundancyFactor: 2
    backendWorkers: 4
    backendPartitions: 2
    memoryProfile: Medium
